dev  pn-f24
pagopa/pn-f24 pull request #3
Opened 2023-09-30 14:20 UTC by empassaro

primo rilascio comprendendo tutti i ticket

2023-10-03 13:20 UTC, fabriziolana requested changes
intanto alcuni commenti (alcuni formali)
rimango in attesa di avere un init.sh per l'esecuzione in locale

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +              - dynamodb:ExecuteTransaction
forse manca l'UpdateItem, mi par sia usato come metodo

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +        ContainerEnvEntry2: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
non credo serva la configurazione dei cors, il microservizio non è esposto al web

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/storage.yml
> +        AttributeName: "ttl"
mi pare che la ttl vada specificata anche tra le colonne in attributesdefinitions

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/storage.yml
> +        AttributeName: "ttl"
idem come sopra

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/storage.yml
> +        DelaySeconds: 2
come parametri userei qualcosa di simile a delivery push:
Parameters:
        QueueName: !Sub '${ProjectName}-f24_internal'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName        
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/CorsGlobalConfiguration.java
>      public void addCorsMappings(CorsRegistry corsRegistry) {
credo appunto che i CORS non serva configurarli in questo microservizio

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +        ContainerEnvEntry11: !Sub 'PN_F24_EVENTBUS_NAME=arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${ProjectName}-CoreEventBus'
mi sarei aspettato di trovare le configurazioni per quanto riguarda i GG di scadenza dei TTL (uno per le richieste non ancora validate a 3gg, l'altro per i documenti generati a 120gg). da aggiungere agli import e al microservice-dev-cfg.json

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/config/RestTemplateFactory.java
> +    public RestTemplate restTemplateWithOffsetDateTimeFormatter(@Value("${pn.commons.retry.max-attempts}") int retryMaxAttempts, @Value("${pn.commons.connection-timeout-millis}") int connectionTimeou
usando webflux, non dovrebbe proprio servire  il resttemplatefactory

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +        ContainerEnvEntry11: !Sub 'PN_F24_EVENTBUS_NAME=arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${ProjectName}-CoreEventBus'
e anche la durata del "retry-after" durante la generazione sincrona

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/service/impl/F24ServiceImpl.java
> +                                .flatMap(f24File -> safeStorageService.getFilePolling(f24File.getFileKey(), false, f24Config.getPollingTimeoutSec(), f24Config.getPollingIntervalSec())
eseguire il polling direttamente su dynamo, ci si può fermare quando lo stato della cache diventa DONE, così non "stressiamo" safe-storage.

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/service/impl/F24ServiceImpl.java
> +                .onErrorResume(ConditionalCheckFailedException.class, e -> {
forse meglio tenere le exceptions dynamo nel layer DAO, eventualmente rimappandole in una eventuale PnDbConflictException o similare

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/middleware/queue/consumer/handler/InternalEventHandler.java
> +                validateMetadataEventService.handleMetadataValidation(payload)
sarebbe utile wrappare con MDCUtils.addMDCToContextAndExecute, così da propagare il contesto mdc.

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/middleware/queue/consumer/handler/InternalEventHandler.java
> +                preparePdfEventService.preparePdf(payload)
sarebbe utile wrappare con MDCUtils.addMDCToContextAndExecute, così da propagare il contesto mdc.

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/middleware/queue/consumer/handler/SafeStorageEventHandler.java
>                      safeStorageEventService.handleSafeStorageResponse(response).subscribe();
sarebbe utile wrappare con MDCUtils.addMDCToContextAndExecute, così da propagare il contesto mdc.

inoltre, usare il .block per essere sicuri che eventuali exception vengano propagate nel thread

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/middleware/queue/consumer/handler/InternalEventHandler.java
> +                generatePdfEventService.generatePdf(payload)
sarebbe utile wrappare con MDCUtils.addMDCToContextAndExecute, così da propagare il contesto mdc.

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/service/impl/MetadataDownloaderImpl.java
> +    public static final BigDecimal RETRY_AFTER_TIME_LIMIT = BigDecimal.valueOf(30000);
sebbene non sia una casistica prevista il fatto di non riuscire a ottenere subito il download url, lascerei comunque questi parametri (retry_After e time_limit) letti da configurazione e non cablati nel codice.

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application-test.properties
spostare in test/resources.
aggiungere anche tutto il necessario per init.sh per inizializzare l'ambiente in locale

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
non serve ri-assegnare i valori, son riconosciuti automaticasmente da spring

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.f24.polling-interval-sec = 2
aggiungere alla con in microservice.yml

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.f24.safe-storage-execution-limit-min = 2
aggiungere alla con in microservice.yml

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.f24.polling-timeout-sec = 10
aggiungere alla con in microservice.yml

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.f24.default-retry-after-milli-sec = 20000
aggiungere alla con in microservice.yml

2023-10-03 13:20 UTC, fabriziolana commented on src/main/resources/application.properties
> +pn.f24.retention-for-f24-files-in-days = 365
aggiungere alla con in microservice.yml

2023-10-03 13:20 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/f24/middleware/dao/f24file/dynamo/F24FileCacheRepositoryImplTest.java
creare test IT con scrittura in testcontainer

2023-10-03 13:20 UTC, fabriziolana commented on scripts/aws/cfn/microservice-dev-cfg.json
aggiungere i parametri che ha senso esporre (vedi altri commenti)

2023-10-03 13:20 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/service/SafeStorageService.java
> +    Mono<FileDownloadResponseInt> getFilePolling(String fileKey, Boolean metadataOnly, Integer pollingTimeoutSec, Integer pollingIntervalSec);
probabilmente non serve, vedi commento nel service

2023-10-03 13:20 UTC, fabriziolana commented on config/logback-local.xml
aggiungere in config un application.properties orientato allo sviluppo:
con bind su porta 8091
che usi questa conf. per i log
con puntamenti a mock di safe-storage
con puntamenti a code/eventbridge locali
con eventuali altri settings per lo sviluppo locale

2023-10-05 07:26 UTC, empassaro commented on scripts/aws/cfn/storage.yml
> +        AttributeName: "ttl"
Ho visto che sullo storage di delivery-push ci sono tabelle con ttl che non includono l'attributo nelle attributesdefinitions, se vuoi posso comunque aggiungerlo.

2023-10-05 07:42 UTC, fabriziolana commented on scripts/aws/cfn/storage.yml
> +        AttributeName: "ttl"
ah ok, se non è obbligatorio non serve allora.

2023-10-09 15:14 UTC, merged