PN-9655: aggiunto ordinamento per pathToken
pagopa/pn-f24 pull request #72
Opened 2024-06-11 15:35 UTC by AnaNiagu

2024-06-11 15:47 UTC, fabriziolana requested changes

2024-06-11 15:47 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/f24/middleware/eventbus/util/PnF24AsyncEventBuilderHelper.java
> +            return String.format("%04d", Integer.parseInt(pathToken.split("_")[1]));
Preferirei usare 
StringUtils.leftPad(pathToken.split("_")[1], 4, "0");
senza passare per il parseInt, così è più resistente ad eventuali cambi futuri.

2024-06-12 06:57 UTC, fabriziolana approved these changes

2024-07-30 16:20 UTC, vincenzo-racca-pa commented
Declianta a favore di: https://github.com/pagopa/pn-f24/pull/74

2024-07-30 16:20 UTC, closed without merging